class clsImages{
  static String onbarding_image1 = "asset/Images/onBoarding_1_image.png";
  static String onbarding_image2 = "asset/Images/onBoarding_2_image.png";
  static String onbarding_image3 = "asset/Images/onBoarding_3_image.png";
  static String redo = "asset/Images/redo.png";
  static String next = "asset/Images/arrow-left.png";
  static String user= "asset/Images/user.png";
  static String arabic= "asset/Images/arabic.png";
  static String lock= "asset/Images/lock.png";
  static String secondRigsterConditionLable = "asset/Images/googlRegisterBy.png";
  static String googleIcon= "asset/Images/Google svg.png";
  static String gift= "asset/Images/gift.png";
  static String barcodScan= "asset/Images/scan-barcode.png";
  static String cloud= "asset/Images/cloud.png";
  static String slideImage= "asset/Images/slideBanner.png";
  static String home= "asset/Images/home.png";
  static String trash= "asset/Images/trash.png";
  static String notification= "asset/Images/notification.png";
  static String setting= "asset/Images/setting.png";
  static String copy= "asset/Images/copy.png";
  static String userAndPassword= "asset/Images/usernameAndPasswordBigIcon.png";
  static String fileAndAssetIcon= "asset/Images/fileAndAssetIcon.png";
  static String mapAndPlace= "asset/Images/mapAndPlace.png";
  static String phonse= "asset/Images/phonse.png";
  static String chate= "asset/Images/chate.png";
  static String schesual= "asset/Images/schesual.png";
  static String link= "asset/Images/link.png";
  static String linkIcon= "asset/Images/linkIcon.png";
  static String mapIcon= "asset/Images/map.png";
  static String shopping= "asset/Images/shopping.png";
  static String booket= "asset/Images/booket.png";
  static String call= "asset/Images/call.png";
  static String more= "asset/Images/more.png";
  static String edit= "asset/Images/edit.png";
  static String star= "asset/Images/star.png";
  static String delete= "asset/Images/delete.png";
  static String mobile= "asset/Images/mobile.png";
  static String folder= "asset/Images/folder.png";
  static String folderIcon= "asset/Images/folderIcon.png";
  static String export= "asset/Images/export.png";
 // static String user  static String notification= "asset/Images/notification.png";AndPassword= "asset/Images/usernameAndPasswordIcon.png";

}